- direction: '1100001'
  selection: '0000011'
  speed: '800'
- direction: '0000000'
  selection: '0000011'
  speed: '800'
- direction: '0000000'
  selection: '0001100'
  speed: '800'
- direction: '1111111'
  selection: '1001111'
  speed: '1024'
- direction: '0000000'
  selection: '1000000'
  speed: '800'
